/**
 * Token registry for Celo mainnet + testnet.
 *
 * SECURITY NOTE: every address below was cross-checked against an
 * authoritative source at build time (docs.celo.org's autogenerated
 * token-contracts page, and gooddollar's own docs for G$). None of these
 * were guessed or pattern-matched from memory — in DeFi code, a wrong
 * contract address is the single most dangerous kind of bug, because it
 * fails silently (funds go somewhere, just not where you meant) rather than
 * throwing. If you add a token yourself, pull the address from
 * https://docs.celo.org/token-addresses or the token's own official docs —
 * never from a block explorer search result or a forum post.
 *
 * Sources checked on 2026-07-13:
 *  - https://docs.celo.org/token-addresses  (Mento currencies, USDC, USD₮)
 *  - https://docs.gooddollar.org/for-developers/core-contracts  (G$)
 */

export type TokenSymbol =
  | "CELO"
  | "USDm" // Mento Dollar (this is the same underlying asset historically called cUSD)
  | "EURm" // Mento Euro (formerly cEUR)
  | "BRLm" // Mento Brazilian Real (formerly cREAL)
  | "KESm" // Mento Kenyan Shilling
  | "NGNm" // Mento Nigerian Naira
  | "GHSm" // Mento Ghanaian Cedi
  | "USDC"
  | "USDT"
  | "GOOD_DOLLAR"; // G$ — NOT a Mento token, separate protocol, included because MiniPay/Celo users hold it widely

export interface TokenInfo {
  symbol: TokenSymbol;
  displayName: string;
  decimals: number;
  address: `0x${string}`;
  testnetAddress?: `0x${string}`;
  /** true for Mento-native currencies tradable directly through the Mento Broker */
  isMentoAsset: boolean;
}

export const CELO_MAINNET_CHAIN_ID = 42220;
export const CELO_SEPOLIA_CHAIN_ID = 11142220;

export const TOKENS: Record<TokenSymbol, TokenInfo> = {
  CELO: {
    symbol: "CELO",
    displayName: "CELO",
    decimals: 18,
    address: "0x471EcE3750Da237f93B8E339c536989b8978a438",
    isMentoAsset: true,
  },
  USDm: {
    symbol: "USDm",
    displayName: "Mento Dollar",
    decimals: 18,
    address: "0x765DE816845861e75A25fCA122bb6898B8B1282a",
    testnetAddress: "0xEF4d55D6dE8e8d73232827Cd1e9b2F2dBb45bC80",
    isMentoAsset: true,
  },
  EURm: {
    symbol: "EURm",
    displayName: "Mento Euro",
    decimals: 18,
    address: "0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73",
    testnetAddress: "0x6B172e333e2978484261D7eCC3DE491E79764BbC",
    isMentoAsset: true,
  },
  BRLm: {
    symbol: "BRLm",
    displayName: "Mento Brazilian Real",
    decimals: 18,
    address: "0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787",
    isMentoAsset: true,
  },
  KESm: {
    symbol: "KESm",
    displayName: "Mento Kenyan Shilling",
    decimals: 18,
    address: "0x456a3D042C0DbD3db53D5489e98dFb038553B0d0",
    testnetAddress: "0xC7e4635651E3e3Af82b61d3E23c159438daE3BbF",
    isMentoAsset: true,
  },
  NGNm: {
    symbol: "NGNm",
    displayName: "Mento Nigerian Naira",
    decimals: 18,
    address: "0xE2702Bd97ee33c88c8f6f92DA3B733608aa76F71",
    testnetAddress: "0x3d5ae86F34E2a82771496D140daFAEf3789dF888",
    isMentoAsset: true,
  },
  GHSm: {
    symbol: "GHSm",
    displayName: "Mento Ghanaian Cedi",
    decimals: 18,
    address: "0xfAeA5F3404bbA20D3cc2f8C4B0A888F55a3c7313",
    isMentoAsset: true,
  },
  USDC: {
    symbol: "USDC",
    displayName: "USD Coin",
    decimals: 6,
    address: "0xcebA9300f2b948710d2653dD7B07f33A8B32118C",
    testnetAddress: "0x01C5C0122039549AD1493B8220cABEdD739BC44E",
    isMentoAsset: false,
  },
  USDT: {
    symbol: "USDT",
    displayName: "Tether USD",
    decimals: 6,
    address: "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e",
    isMentoAsset: false,
  },
  GOOD_DOLLAR: {
    symbol: "GOOD_DOLLAR",
    displayName: "GoodDollar",
    decimals: 18,
    address: "0x62B8B11039FcfE5aB0C56E502b1C372A3d2a9c7A",
    isMentoAsset: false,
  },
};

/**
 * Tokens the strategy is allowed to consider trading between. This is a
 * *suggestion* for the off-chain scanner — the real enforcement point is
 * each user's AgentVault.allowedTokens on-chain, which the user controls.
 * Keep this list short at first; every currency you add is another price
 * feed the scanner has to poll and another pair the vault owner has to
 * explicitly allow-list and cap.
 */
export const DEFAULT_STRATEGY_TOKENS: TokenSymbol[] = ["USDm", "KESm", "NGNm", "EURm", "USDC", "USDT", "CELO"];

export function tokenAddress(symbol: TokenSymbol, chainId: number = CELO_MAINNET_CHAIN_ID): `0x${string}` {
  const info = TOKENS[symbol];
  if (chainId === CELO_SEPOLIA_CHAIN_ID && info.testnetAddress) return info.testnetAddress;
  return info.address;
}
